zextras/carbonio-proxy

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
If we don't specify the http version envoy answer with a http 426, asking the client to upgrade to http/2.0.
To avoid this error we simply specify http version 1.1 to nginx.
see https://github.com/envoyproxy/envoy/issues/2506
=> envoy proxy doesn't like http 1.0, force http version 1.1 when reverse proxying

package/PKGBUILD
service-discover and pending setups should be carbonio-core dependencies, because shared between multiple components. This also fix some issues on files and folders detection during the postinst phase
=> refactor(packages): CO-37: enable multiserver installations

conf/nginx/templates/nginx.conf.web.carbonio.admin.default.template
set /carbonioAdmin url rewrite to legacy admin console
=> feat: nginx.conf.web.carbonio.admin.default.template

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
This ensures the user is properly logged out when the logout call is made using IRIS logout method and the legacy web app is not installed.
=> fix: properly logout in IRIS UI

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
**Key changes:**
- IRIS is set to the standard UI if the UI cookie is not set.
- The classic app is loaded by default if a UI cookie is set and the classic app is installed.
=> chore:[CO-331] fix UI cookie behavior

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
- this is a temporary workaround to ensure appropriate functionality until the login component is updated.
=> fix: also redirect to iris shell if UI cookie is set to iris  

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
I've added locations for /services/chats/events to proxy pass a websocket
=> feat: [CHATS-353] add location for chats events websocket

conf/nginx/templates/nginx.conf.web.carbonio.admin.default.template, conf/nginx/templates/nginx.conf.web.carbonio.admin.template
- redirect to login page if location is / and no admin cookie exists
- redirect to admin panel if location is / and admin cookie exists (check for valid cookie happens on first SOAP request)
=> feat: [CO-494] Add sane redirection rules for Carbonio Admin UI

conf/nginx/templates/nginx.conf.web.http.default.template, conf/nginx/templates/nginx.conf.web.http.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
**What has changed:** 
- Logout operation now also removes ZX_AUTH_TOKEN
The removal was defined already, but the redirect check was preventing it from happening. This was fixed by changing the order of rules.
=> fix: [CO-501] remove ZX_AUTH_COOKIE during Logout operation

conf/nginx/templates/nginx.conf.web.carbonio.admin.default.template, conf/nginx/templates/nginx.conf.web.carbonio.admin.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
- expand proxy http compression variable(proxy.http.compression) in server entries
- carbonio-web app
- carbonio-web-admin app
**Related PRs:**
- https://github.com/Zextras/carbonio-mailbox/pull/176
- https://github.com/Zextras/carbonio-jetty-conf/pull/6
=> feat: [CO-620] Enable gzip and brotli compression in proxy

conf/nginx/templates/nginx.conf.stream.message.dispatcher.xmpp.template, conf/nginx/templates/nginx.conf.stream.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template, conf/nginx/templates/nginx.conf.web.template, package/carbonio-proxy.hcl
Since **chats** and **chats-messaging** services have been renamed into **ws-collaboration** and **message-dispatcher,** also these files have to be changed in order to let everything works properly.
Related PR: https://github.com/Zextras/carbonio-mailbox/pull/199
=> chore: [CHATS-771] Rename chats and chats-messaging upstreams

conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template, conf/nginx/templates/nginx.conf.web.template, package/carbonio-proxy.hcl
Hello everyone,
this PR enables `carbonio-auth` access through the service mesh:
=> chore: [AUTH-417] Access auth via service mesh

package/carbonio-proxy
- Proxy service ACL token now lives in new path /etc/carbonio/proxy/service-discover/token
**Tests:**
- deployed changes on VM and ran pendin-setups to run proxy setup
- new token in created followed by consul reload
- all services are working as expected
=> feat: [CO-677] Change path of service acl policy token

conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
- In order to uniform the logout handling across Admin UI and Web UI, separate logout path was added in the Web proxy templates targeting Default and VirtualHost proxy config.
- The old query parameter based (loginOp=logout) endpoint will be removed in next version of Carbonio, Deprecation note has been added to imply the same in the template.
=> feat: [CO-813] Add logout endpoint to handle user logout

conf/nginx/templates/nginx.conf.web.admin.default.template, conf/nginx/templates/nginx.conf.web.admin.template, conf/nginx/templates/nginx.conf.web.carbonio.admin.default.template, conf/nginx/templates/nginx.conf.web.carbonio.admin.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
- minor cleanup targetting unification of web templates.
- new variables to support redirection of web login and logout for both default and virtualhost templates all defaulting to /static/login/ path
- for handling login `web.carbonio.[webui|admin].login.url.[default|vhost]`
- for handling logout `web.carbonio.[webui|admin].logout.redirect.[default|vhost]`
**Related PRs:**
- https://github.com/zextras/carbonio-mailbox/pull/301
**Note:** the redirection of logout is handled by othe carbonio components like UI and Auth.
**DO NOT SQUASH**
=> feat: [CO-772] Add support for custom login/logout URL for domains

conf/nginx/templates/nginx.conf.web.carbonio.admin.default.template, conf/nginx/templates/nginx.conf.web.carbonio.admin.template, conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
-  start mapping the /favicon.ico location to 404 error
ref: CO-855
=> fix: [CO-855] Carbonio shows Jetty favicon instead of Carbonio one

conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
Added two rules to fetch the [carbonio-files-public-folder-ui](https://github.com/zextras/carbonio-files-public-folder-ui) bundle necessary to access a carbonio-files public folder without authentication.
The first rule is tied to the `/files/public/link/access/assets/` endpoint and it allows to download all the assets required by the bundle.
The second rule is tied to the `/files/public/link/access/` endpoint and it downloads the index.html of the bundle.
Ref: FILES-734
=> feat: add nginx rule to fetch carbonio-files-public-folder-ui bundle

package/proxy/carbonio-proxy.target
This is a QA-fix and should be back-merged in devel.
After the merge in main a new tag and version should be forged
=> chore: systemd: make targets able to be enabled at boot

conf/nginx/templates/nginx.conf.main.template
pidfile path is now managed at [built-time](https://github.com/zextras/carbonio-thirds/blob/b514f7c7f9b271fd4a426b035132f8f7d566414d/native/nginx/PKGBUILD#L80) and not configurable anymore
=> chore: remove .pid files references

conf/nginx/templates/nginx.conf.web.clamav.signature.provider.template
According to https://github.com/zextras/carbonio-avdb-updater/pull/29
Changed directory name:
from  av_signature
to av_signatures
=> fix: wrong folder name where to download local signatures

conf/nginx/templates/nginx.conf.mail.template
fix: order of ssl certs exposed for imaps/pop3s
=> fix: order of ssl certs exposed for imaps/pop3s

conf/nginx/templates/nginx.conf.web.https.default.template, conf/nginx/templates/nginx.conf.web.https.template
- RobotsServlet was removed from the mailbox but we decided to keep /robots.txt and keep web crawlers out (old default behavior) for the whole infrastructure, not just the /service endpoint
See: https://github.com/zextras/carbonio-mailbox/pull/723
=> feat: [CO-2051] add /robots.txt to keep web crawlers out

Dockerfile, Jenkinsfile, entrypoint.sh
This container is based on mailbox dev container, as it needs mailbox jars to run zmproxyconfgen.
It uses carbonio-nginx from release + adds the files under conf.
At runtime the container creates a proxy server with proxy and memcached services installed, expands the templates and starts with daemon off.
In order to use this container nginx-zmlookup is required (it has been added to mailbox in: https://github.com/zextras/carbonio-mailbox/pull/759) and also a memcached instance is required.
We tested it successfully locally, but few things are required in order to use it:
- mailbox with zmlookup
- memcached
- (optional) no webui is provided, this is only the proxy configuration. If you need a webui you have several options, like running apt install carbonio-webui in the container manually …
=> chore: define proxy dev container

Jenkinsfile, yap.json
This PR updates the Jenkins pipeline to use the newly released jenkins-packages-build-library v1.0.0, which introduces major improvements to our build infrastructure:
Key Benefits:
1. reduce duplicated code
2. centralized configuration for supported platforms (ubuntu-jammy, ubuntu-noble etc.)
3. reutilize the playground rt project to test the pipeline release flow
These changes significantly reduce pipeline complexity while making builds more maintainable and reliable across all Zextras repositories.
=> chore (ci): upgrade to jenkins-packages-build-library@1.0.0

entrypoint.sh
Fix the `entrypoint.sh` script by setting the correct path for the upstreams definitions file
=> build: fix env variables replacement
